### ISSUE TITLE
ScenarioBuilder extendability 

### ISSUE THREAD

**Issue by nismolo** [LightBDD/LightBDD#102]
We are implementing extensions on the fluent scenario builder to be able to run scenarios according to configuration data while running the tests. For example run specific tests only on specific environments (QA / Prod). 

We have implement the feature by creating an extension method  on the runner methods. 

#### Extended Extension
```cs
public static async Task RunScenarioActionOnEnvironmentAsync<TContext>(
        this IBddRunner<TContext> runner,
        string env,
        params Expression<Action<TContext>>[] steps
)
{
    if (env.Equals(ConfigEnv))
    {
        await runner.RunScenarioActionsAsync(steps);
    }
    else
    {
        StepExecution.Current.IgnoreScenario(_message);
    }
}
```

#### Fluent Extension
```cs
public static async Task RunOnEnvAsync<TContext>(
    this IScenarioBuilder<TContext> builder,
    string env
)
{
    if (env.Equals(ConfigEnv))
    {
        await builder.RunAsync();
    }
    else
    {
        StepExecution.Current.IgnoreScenario(Message);
    }
}
```

Ideally, instead we want to add an extension method to be able to filter test scenarios which would be much cleaner + we can add more filters.
But to implement such a feature we require to have a Dictionary in the `ScenarioBuilder` class to be able to add specific filters. 

#### Usage

```cs
// extensions
public static IScenarioBuilder<TContext> FilterEnv<TContext>(this IScenarioBuilder<TContext> builder, string env)
{
    builder.Items.Add("ENV", env);
    return builder;
}

public static async Task RunWithFilters<TContext>(this IScenarioBuilder<TContext> builder)
{
    string env = (string)builder.Items["ENV"];
    if (env.Equals(ConfigEnv))
    {
        await builder.RunAsync();
    }
    else
    {
        StepExecution.Current.IgnoreScenario(Message);
    }
}
```

``` cs
// usage in feature specs
public async Task Browsing_invoices()
{

    await Runner
        .NewScenario()
        .FilterEnv("QA") // our extension method
        .AddAsyncSteps(
            _ => Given_invoice("Invoice-1"),
            _ => Given_invoice("Invoice-2"))
        .AddSteps(
            When_I_request_all_historical_invoices)
        .AddSteps(
            _ => Then_I_should_see_invoices("Invoice-1", "Invoice-2"))
        .RunWithFilter(); // our extension method
}
```

If you agree I am happy to create a PR.

**Comment by Suremaker** [comment]
Hey, I'm right now on holidays and will be able to take a closer look on your request next week (after 29th).

I wonder however if the existing feature of IScenario/IStepDecoratorAttribute added in LightBDD 2.3.0 will work for you out of the box?

Take a look at sample [IgnoreScenarioAttribute]( https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.NUnit3/IgnoreScenarioAttribute.cs).

You could implement the filter like that:

```c#
[AttributeUsage(AttributeTargets.Method)]
public class FilterAttribute : Attribute, IScenarioDecoratorAttribute
{
    private string[] _filters;
    public  FilterAttribute(params string[] filters) { _filters = filters; }

    public Task ExecuteAsync(IScenario scenario, Func<Task> scenarioInvocation) 
    { 
        if (filters.Any(f => f == ConfigEnv))
            StepExecution.Current.IgnoreScenario(/* ... */);
        else
            await scenarioInvocation();
    }
}
```

Then usage would be:
```c#
// usage in feature specs public async Task
[Filter("QA")] //<-- applied here
Browsing_invoices()
{ 
    await Runner
        .NewScenario()
        .AddAsyncSteps(
            _ => Given_invoice("Invoice-1"),
            _ => Given_invoice("Invoice-2"))
        .AddSteps( When_I_request_all_historical_invoices)
        .AddSteps(
            _ => Then_I_should_see_invoices("Invoice-1", "Invoice-2"))
        .RunAsync();
}
```

(I wrote it by hand so may not compile - sorry about that)...


Also you can make attribute implementing IStepDecoratorAttribute and then even decorate step methods.

It naturally supports multiple attributes (with ordering) so you should be able to implement multiple filters.

Finally it is also possible to register decorators globally during config with `ExecutionExtensionsConfiguration()` - unfortunately I have not provided wiki about it, so only method docs is available in code and sample tests.

-----
Let me know if such solution will be applicable to your needs... If not, I will be take a closer look on your request next week

**Comment by Suremaker** [comment]
Another example is [MultiAssertAttribute](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Framework/MultiAssertAttribute.cs) that is done in the same way.

**Comment by nismolo** [comment]
Hey Thanks for your feedback. We decided to go forward with your proposed solution since its cleaner then what we originally intended to use. 

> Also you can make attribute implementing IStepDecoratorAttribute and then even decorate step methods. It naturally supports multiple attributes (with ordering) so you should be able to implement multiple filters.

Can you please show us an example of an implementation which uses StepDecoratorAttribute in your code since we might require it for the future.

Thanks & keep up the great work with lightbdd! 👍

**Comment by Suremaker** [comment]
Cool, it's good to hear it works for you.

In fact both mentioned attributes works on step and scenario methods as they implement both decorator interfaces.

See how the IgnoreScenarioAttribute implements IStepDecoratorAttribute here: https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.NUnit3/IgnoreScenarioAttribute.cs

... while example usage is described here: https://github.com/LightBDD/LightBDD/wiki/What-Is-New#2-declarative-way-for-ignoring-scenarios-and-steps

**Comment by nismolo** [comment]
Something not related to this question, is there a lightbdd channel/room on gitter?

**Comment by Suremaker** [comment]
Hey, I did not have gitter before but created room there (https://gitter.im/LightBDD/LightBDD) and sent you an invite.
Will add it to repo readme as well as I think it may be easier to ask questions there than via github issues
