### ISSUE TITLE
Allow IStepDecoratorAttribute and IScenarioDecoratorAttribute to be applied on class level

### ISSUE THREAD

**Issue by tpodolak** [LightBDD/LightBDD#108]
#### Description
Current implementation of LightBDD recognizes ``IScenarioDecoratorAttribute`` and ``IStepDecoratorAttribute`` only if they are applied to the methods. It would be beneficial if the runner could also take into account attributes applied on the class level. For instance if I want to run all of the tests from given class only for specific environment ([like it is done in here](https://github.com/LightBDD/LightBDD/issues/102#issuecomment-359619296)) I would be able to apply only one class level attribute.

**Comment by Suremaker** [comment]
Hello,

Thanks for reporting it. I'm on holidays at the moment but will take a closer look on it after return next week.

There should not be many issues with adding this behaviour, but I will have to analyse how it would work with contextual scenarios where steps can be defined in context class or composites.
Currently the way I see it would be simply respecting the decorators added on method or class **where method is defined**.

Let me come back to you after Tuesday.

**Comment by Suremaker** [comment]
Btw, to be precise, using method level attribute is not the only way to install scenario/step decorators.
They can be also applied globally on all classes/methods with [LightBDD configuration](https://github.com/LightBDD/LightBDD/wiki/LightBDD-Configuration#configurable-lightbdd-features) (ExecutionExtensionsConfiguration()) method.

**Comment by Suremaker** [comment]
Released with 2.3.6
