### ISSUE TITLE
Add [F7] Shortcuts To Switch Between Features & Steps

### ISSUE THREAD

**Issue by jaywha** [LightBDD/LightBDD#112]
#### Description
As I am coding, I like to have the Features on one side and my Steps on the other.  
It isn't too much of a hassle as is to open the files, but I've been learning to use Resharper/CodeRush to speed up my coding.  

**Just as other files have "code behind", pressing _[F7]_ should go to the Steps and _[Shift]+[F7]_ goes back to the Features.**  

Very small request, and also not super imperative, but I thought it'd be a neat little thing to add to improve similarity with other components of Visual Studio:

- WPF [.xaml/.xaml.cs]

- Winforms [Designer/Code]

- ASP.NET [lit. CodeBehind]

Link to related concept: https://goo.gl/JPCsGp  

#### Progress
- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience,
- [ ] Celebrate 🎉

**Comment by Suremaker** [comment]
Hey, @jaywha .

Thanks for reporting this. I will take a look what can I do to make it working better.
In Resharper I am always using F12 shortcut after selecting the class name to jump between files with steps and scenarios (assuming that they are implemented with partial class).

**Comment by Suremaker** [comment]
I did a quick check and there are few options.

Assuming you have following files:
**My_feature.cs**:
```c#
public partial class My_feature: FeatureFixture
{
    [Scenario]
    public void My_scenario()
    {
        Runner.RunScenario(
            _ => Given_step(),
            _ => When_step(),
            _ => Then_step()
        );
    }
}
```
and **My_feature.Steps.cs**:
```c#
public partial class My_feature
{
    private void Given_step()
    {
    }

    private void When_step()
    {
    }

    private void Then_step()
    {
    }
}

With Resharper, you can do a following things:
* In any of the files, right click on `My_feature` class and select `Go To Definition` (F12 shortcut) - it will iterate through the class parts (I use this method quite often),
* In `My_feature.cs` file, right click on `_ => Given_step()` select `Go To Definition` (F12 shortcut) - it will bring you to the definition of the step. If you do it again while being in `My_feature.Steps.cs`, it will iterate through all the usages of that step,
* You can select `My_feature` class and press `Ctrl+Alt+F7` that will bring you to the related files as well, but I did not find it that handy,

I am using R# 2018.1, but I was using F12 shortcut for a long time now so definitely it works with previous R# as well.

There are some more information on the shortcuts: https://stackoverflow.com/questions/17666349/a-shortcut-to-jump-between-partial-classes

I found also a shortcut for vanilla VS where you can move cursor over the method or class name and press `Ctrl+F3` or `Shift+F3` to navigate forward and backward between the name occurrences.

Source: https://stackoverflow.com/questions/1888161/navigating-through-code-with-keyboard-shortcuts

Please let me know if that works for you or if I misunderstood you anyhow.

I hope it helps!

**Comment by jaywha** [comment]
This is absolutely perfect.  
I should've done a bit more digging myself apparently.  
I appreciate the quick response. :+1:
