### ISSUE TITLE
Support combinatorial test case generation like NUnit does with Values attribute

### ISSUE THREAD

**Issue by SashaPshenychniy** [LightBDD/LightBDD#144]
#### Description
NUnit supports creating combinatorial test cases using [Values attribute](http://nunit.org/docs/2.5/values.html) on test arguments:
```
[Test]
public void MyTest(
    [Values(1,2,3)] int x,
    [Values("A","B")] string s)
{
    ...
}
```
As far as I can see, LightBDD currently only supports TestCaseData and TestCaseSource attributes and it is quite complex to set up all combinations of values (needs some additional coding).

Also would be nice to support [Combinatorial] and [Pairwise] attributes since full join of test values may result in unmanageable number of test cases sometimes. 
Step forward would be to have extensibility point here and allow creating own logic for combining test cases values. This could be done with TestCaseSource, but applying an attribute is much easier than creating specific test case generator for each test method.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello @SashaPshenychniy ,

The LightBDD is built on top of the test frameworks so you should be able to use any of the NUnit features to write LightBDD scenarios.

Let's see the an example:
```c#
public class My_feature : FeatureFixture
{
    [Scenario]
    public void Concatenating_number_with_text(
        [Range(2, 5)] int number,
        [Values("cats", "dogs")] string text)
    {
        Runner.RunScenario(
            _ => Given_a_number(number),
            _ => Given_a_text(text),
            _ => When_I_concatenate_it(),
            _ => Then_I_should_receive_result($"{number} {text}"));
    }

    private int _number;
    private string _text;
    private string _result;

    private void Given_a_number(int number) => _number = number;
    private void Given_a_text(string text) => _text = text;
    private void When_I_concatenate_it() => _result = $"{_number} {_text}";
    private void Then_I_should_receive_result(string result) => Assert.AreEqual(result, _result);
}
```

and the outcome:
![image](https://user-images.githubusercontent.com/1894621/45423988-fb254300-b68c-11e8-955b-b46642812097.png)


Now, let's play with [Combinatorial] and [Pairwise] attributes on scenario from a sample blog: https://www.stevefenton.co.uk/2015/04/combinatorial-and-pairwise-testing-with-nunit/

```c#
public class My_feature : FeatureFixture
{
    [Scenario, Combinatorial]
    public void Combinatorial_scenario(
        [Values(1, 2, 3, 4)] int a,
        [Values("A", "B", "C")] string b,
        [Values("x", "y", "z")] string c)
    {
        Runner.RunScenario(_ => Given_a_b_c(a, b, c));
    }

    [Scenario, Pairwise]
    public void Pairwise_scenario(
        [Values(1, 2, 3, 4)] int a,
        [Values("A", "B", "C")] string b,
        [Values("x", "y", "z")] string c)
    {
        Runner.RunScenario(_ => Given_a_b_c(a, b, c));
    }

    private void Given_a_b_c(int a, string b, string c){}
}
```
![image](https://user-images.githubusercontent.com/1894621/45424263-e301f380-b68d-11e8-9ccf-17e313463320.png)

**Comment by Suremaker** [comment]
Please let me know if this is what you have been looking for?

**Comment by SashaPshenychniy** [comment]
@Suremaker Sorry for not investigating the case enough - it seems I've missed Values attribute on one of my boolean arguments and thought it's obvious that all (both) values are expected. And I already managed to implement combinatorial test generator on my own =)).
I've double-checked now and all works fine like with NUnit, so sorry again for bothering.

**Comment by Suremaker** [comment]
No problem, you are welcome.
