### ISSUE TITLE
Tidy up output when local functions are used for steps

### ISSUE THREAD

**Issue by dday4thedeceiver** [LightBDD/LightBDD#155]
#### Description

This won't really be an issue if steps can be inlined, but currently to take advantage of IDE outlining and create self-contained scenarios, local functions are helpful. The problem is using them duplicates the scenario title / parent method name in the Step output.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
I took a second look at this issue and decided to close it at this moment with **won't fix** label.

There are two reasons for this:
1. It is currently not possible to retrieve the original name of the local function at runtime as all the local function names get mangled upon compilation (to form like `<GetStepName_should_interpret_local_functions>g__Some_step|1_0`) and there is no reflection api allowing to obtain the original name,
2. Local functions are not supported in expression trees ([here is a link to the issue](https://stackoverflow.com/questions/44228502/an-expression-tree-may-not-contain-a-reference-to-a-local-function)) which means that it won't be possible to use [extended syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#extended-scenarios).

It means that I would need to implement custom parsing logic for the names, relying on the implementation details of the C# compiler to extract names of local function, and even if I do this, the only scenario where it would be possible to use it would be the [basic syntax](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#basic-scenarios).

Closing it in favor of #156
