### ISSUE TITLE
Output from tests not showing correct step text in Visual Studio 2017.

### ISSUE THREAD

**Issue by TheTFo** [LightBDD/LightBDD#165]
#### Description

Viewing the output from tests in Visual Studio does not show the step names for each step. Instead it shows the scenario name.

![image](https://user-images.githubusercontent.com/530080/49675572-4a88ce80-fa44-11e8-9b26-b23fac90a189.png)

Also, the steps do not show in the HTML report:

![image](https://user-images.githubusercontent.com/530080/49675858-5628c500-fa45-11e8-860a-9ff59fbc5afd.png)

Added a basic feature and scenario and ran the tests.

I'm using: 
VS 2017 Pro 15.8.8
XUnit 2.4.1
XUnit.Runner.VisualStudio 2.4.1
LightBDD.XUnit2 2.5.0

I also tested with 2.4.3 and still see the same problem.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello,

I am guessing that you used `using LightBDD.Framework.Scenarios.Basic` namespace but written scenario steps with lambda style like `() => Given_xxx()`.

Please ensure that you are using right namespaces for the right scenario styles:
* [basic](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#basic-scenarios),
* [extended](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#extended-scenarios),
* or other described on pages above.

Please let me know if that helps.

**Comment by TheTFo** [comment]
I believe this is my issue. I'll report back.

Is there a way to determine this problem and notify users? I think a test
of whether a method is anonymous is possible.

**Comment by Suremaker** [comment]
Perfect.  
The linked wiki page contains all the styles that LightBDD supports, so I hope there will be one fulfilling your needs.

> Is there a way to determine this problem and notify users?

Yes, I thought about the same when I was replying to the issue. There is no point to allowing anonymous methods in basic scenarios. With the new version I will add validation that will throw exception in such situation.

**Comment by TheTFo** [comment]
I've confirmed after switching namespaces that my issue is resolved.  Thanks!

**Comment by Suremaker** [comment]
Great, thank you. The new version of LightBDD will offer a better support for detecting those issues.

**Comment by Suremaker** [comment]
Implemented in LightBDD 3.0
