### ISSUE TITLE
Create a new resource per Scenario, but reuse in Decorator

### ISSUE THREAD

**Issue by dstj** [LightBDD/LightBDD#189]
#### Description
(This is a bit of a follow-up to #186...)

Using `builder.RegisterType<ResourceHandle<ChromeDriver>>().InstancePerLifetimeScope();` creates a single `ChromeDriver` used in all scenarios. This is good so that my `TakeScreenshotOnError` decorator retrieves the current ChromeDriver to take a screenshot.

But, for some reason (unrelated to LightBDD), I'm not able to clear the browser's LocalStorage as the first step in every scenarios (and since each test requires a clean browser, the 2nd, 3rd, etc. test fail), so reusing the same ChromeDriver in every scenario is not a working solution. I need to create a new one.

How could I have a new `ChromeDriver` for every scenario, but in a manner that my decorator gets the current scenario's driver?

I tried injecting `ResourcePool<ChromeDriver> driverPool` in my context classes to manually dispose and recreate the driver, as following:

```c#
protected SeleniumBaseTestContext(ResourcePool<ChromeDriver> driverPool, ResourceHandle<ChromeDriver> driverHandle)
{
	_driverPool = driverPool;
	_driverHandle = driverHandle;
}

public async Task Given_that_the_browser_is_clean()
{
	var driver = await _driverHandle.ObtainAsync();
	if (driver.Url != "data:,") {  // Means that the driver is NOT new
		_driverHandle.Dispose();
		_driverHandle = _driverPool.CreateHandle();
	}
}
```
but it does not replace the instance in the DI and the decorator retrieves a disposed instance.

My only other idea is to register in the DI a `ChromeDriverManager` class that would basically replace the `ResourcePool` and allow recreating the driver instance when required.

Thanks.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello @dstj,

I would suggest then to use `ChromeDriver` directly without `ResourcePool` nor `ResourceHandle`.

If you specify: `builder.RegisterType<ChromeDriver>().InstancePerLifetimeScope()` you should get them one per scenario.

**Comment by dstj** [comment]
@Suremaker 
Thanks, using `builder.Register(c => CreateDriver()).InstancePerLifetimeScope();`  seems to do the trick.  I reread the section about [DI Scopes in the documentation](https://github.com/LightBDD/LightBDD/wiki/DI-Containers#container-scopes) and now was able to better understand the `ResourceHandle`, `ResourcePool` impact...
