### ISSUE TITLE
[question] Background keyword support

### ISSUE THREAD

**Issue by tuscias** [LightBDD/LightBDD#190]
Hi, is there a way to make something similar to gherkin background keyword, e.g.: 
"""
Background: Given App was started
                       And user is logged in
"""

Thanks!

**Comment by Suremaker** [comment]
Hello @tuscias ,

By reading [gherkin docs](https://cucumber.io/docs/gherkin/reference/#background) I understand that `background` allows to group setup steps that should be executed on each scenario in the feature.

The closest equivalent in LightBDD would be to use [composite steps](https://github.com/LightBDD/LightBDD/wiki/Composite-Steps-Definition) to define the `background step` but then call it at the beginning of every scenario.

Here is an example:

```c#
public class Shopping : FeatureFixture
{
    private CompositeStep Background_I_am_buying_clothes()
    {
        return CompositeStep.DefineNew()
            .AddSteps(
                _ => Given_there_are_COUNT_PRODUCT_products_on_the_stock_priced_COST_each(3, "black sweater", 35),
                _ => Given_there_are_COUNT_PRODUCT_products_on_the_stock_priced_COST_each(3, "green t-shirt", 10),
                _ => Given_I_have_AMOUNT_in_my_wallet(100))
            .Build();
    }

    [Scenario]
    public void Buying_products()
    {
        Runner.RunScenario(
           _ => Background_I_am_buying_clothes(),
           _ => Given_I_want_to_buy_COUNT_items_of_PRODUCT(2, "black sweater"),
           _ => Given_I_want_to_buy_COUNT_items_of_PRODUCT(2, "green t-shirt"),
           _ => When_I_proceed_with_transaction(),
           _ => Then_transaction_should_succeed(),
           _ => Then_I_should_have_AMOUNT_pounds_left_in_my_wallet(10));
    }

    [Scenario]
    public void No_items_in_stock()
    {
        Runner.RunScenario(
            _ => Background_I_am_buying_clothes(),
            _ => Given_I_want_to_buy_COUNT_items_of_PRODUCT(4, "black sweater"),
            _ => When_I_proceed_with_transaction(),
            _ => Then_transaction_should_fail_with_error("There is not enough products: black sweater"),
            _ => Then_I_should_have_AMOUNT_pounds_left_in_my_wallet(100));
    }

    [Scenario]
    public void Not_enough_money()
    {
        Runner.RunScenario(
            _ => Background_I_am_buying_clothes(),
            _ => Given_I_want_to_buy_COUNT_items_of_PRODUCT(3, "black sweater"),
            _ => When_I_proceed_with_transaction(),
            _ => Then_transaction_should_fail_with_error("Not enough funds"),
            _ => Then_I_should_have_AMOUNT_pounds_left_in_my_wallet(100));
    }
   /* ... */
}
```

The outcome would be then as follows:
![image](https://user-images.githubusercontent.com/1894621/61746096-d90f4d80-ad92-11e9-8b3d-af9ebf5574c8.png)

Also, as the `background` is not a built-in step type, you may need to add it on the `ConfiguredLightBddScope`:

```c#
internal class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
{
    protected override void OnConfigure(LightBddConfiguration configuration)
    {
        configuration.StepTypeConfiguration()
            .UpdatePredefinedStepTypes("given", "when", "then", "and", "background");
    }

    protected override void OnSetUp()
    {
        // code executed before any scenarios
    }

    protected override void OnTearDown()
    {
        // code executed after all scenarios
    }
}
```

By the way, if you rename `Background_I_am_buying_clothes()` to `Setup_I_am_buying_clothes()`, you won't need to reconfigure LightBDD as `setup` is a predefined type (see [steps auto grouping](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#steps-auto-grouping) wiki page for details).

----

Please note also that it is possible to decorate the scenarios and steps with [decorators](https://github.com/LightBDD/LightBDD/wiki/Extending-Test-Behavior#scenario-and-step-decorators), but they are more suitable for the setup/tear down operations that should happen in the background (they are not included in the progress nor reports), and I guess it is not something you are interested in at this moment.

Please let me know if that helps,
Cheers

**Comment by tuscias** [comment]
Thank you very much for such detailed answer!

I was thinking of introducing a new [Background] attribute that would be used with Nunit's [SetUp] attribute and somehow appear only once in the feature report just above all scenarios.

**Comment by Suremaker** [comment]
> I was thinking of introducing a new [Background] attribute that **would be used with Nunit's [SetUp] attribute** and somehow **appear only once** in the feature report just above all scenarios.

If we would think to implement it there would be a problem with making it right. The `[SetUp]` method like the mentioned [Gherkin background](https://cucumber.io/docs/gherkin/reference/#background) steps are run **for each** scenario which means that such code is not executed once per feature but potentially many times. Having said that, it would be difficult to display it once within the feature as:
* the steps can be parameterized and dynamic, so they may produce different output for each scenario,
* the background steps may fail for some of the scenarios while pass for others.

So, assuming that those steps will have to run per scenario, it is more correct to display them per scenario basis as they may have different characteristics / outcomes. Then, the example presented above is behaving like that.

---

If the expectation is to run this background code once per feature and display it once, then at this moment there is no such feature in the LightBDD. The closest what you could get is to:
* use constructor / `[OneTimeSetup]` attribute in NUnit to call the background code once,
* use [FeatureDescription](https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions#test-classes-structure) attribute to describe the background, but please be aware that this would be a static description that may get easily out of sync with the setup code.

I hope that helps
