### ISSUE TITLE
Modernise HTML reports

### ISSUE THREAD

**Issue by Suremaker** [LightBDD/LightBDD#207]
#### Description
The HTML report is a few years old and looks pretty outdated. This ticket is a high level epic about revisiting the report layout, features and visualization to modernize it.

Aspects to cover:
### Look & Feel
- [x] Font refresh
- [x] Execution summary refresh with header bar and logo
- [x] Feature summary refresh
- [x] Feature details refresh
- [x] Feature label tags refresh
- [x] Feature category tags refresh
- [x] Toggle and radio buttons refresh
- [x] Update representation of the scenario/step status 
- [x] Tabular parameters visual refresh
- [x] Tree-like parameters visual refresh
- [x] Refresh links & anchors
- [x] Refresh error messages
- [x] Refresh comment messages
- [ ] Refresh report title - to be done as part of #290 
- [ ] Address font flickering on load - no action taken
- [x] Theme colors review
### Customizations
- [x] Css override
- [x] Logo override
### Compatibility checks
- [x] Chrome
- [x] Friefox
- [x] Edge
- [x] Android
- [x] IOS ?
- [x] Print
- [x] Word copy
- [ ] PowerPoint copy

To consider:
* graphical visualization
* timeline view?
* stats on long running tests?
### Business
* business/story oriented view
* plain story view (to support simple copy paste)
### Usability
* toggle time display
* sorting, filtering, search
* shareable links to all actions (filters, views, items)
* progressive reports allowing to capture testas as they runs

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by lemonlion** [comment]
I think taking a look at at BDDfy report would be a good starting point.  I was recently shown one, and it definitely looks a lot more modern.  Even though the repo itself is no longer being maintained, they still appear to be the only direct competitor in this space.

**Comment by Suremaker** [comment]
Work in progress version of the new HTML Report: [example](https://htmlpreview.github.io/?https://github.com/LightBDD/LightBDD/4b29463d4531e3c7e0272f744d7c516b8fcf1d6b/examples/ExampleReports/FeaturesReport.html)

**Comment by Suremaker** [comment]
Work in progress version of the new HTML Report: [example](https://htmlpreview.github.io/?https://github.com/LightBDD/LightBDD/6f5e14e46deecdd5ef27c61ed18e2db13e42d26e/examples/ExampleReports/FeaturesReport.html)

... to compare, this is the existing report: [link](http://htmlpreview.github.io/?https://github.com/LightBDD/LightBDD/blob/master/examples/ExampleReports/FeaturesReport.html)

**Comment by Suremaker** [comment]
Released with LightBDD 3.7.0
