### ISSUE TITLE
XUnit Theory tests

### ISSUE THREAD

**Issue by srivathsah** [LightBDD/LightBDD#208]
Hi, Thanks for this excellent library. I am at the verge of converting my Xbehave tests to compact LightBDD tests. However the block at the moment is Scenario from LightBDD.Xunit2 is derived from Fact and I am not sure how to do theory tests using xunit. I also see that you have provided some examples for test cases but all of them are using Nunit3. Could you please give me some guidance how I can proceed? Thanks again

**Comment by Suremaker** [comment]
Hello @srivathsah,

Please feel free to use `[Scenario]` with `[InlineData]`, the LightBDD supports the parameterized tests by default. It just uses scenario in both cases as documented on: https://github.com/LightBDD/LightBDD/wiki/Test-Framework-Integrations#lightbddxunit2

**Comment by srivathsah** [comment]
@Suremaker Thanks a lot. and please forgive my ignorance, I did not get that in the docs, I just looked into examples and started checking the Scenario class in Visual Studio.
