### ISSUE TITLE
Work with Autofac?

### ISSUE THREAD

**Issue by archimate** [LightBDD/LightBDD#209]
#### Description
My project  had use Xunit.Ioc.Autofac,
![image](https://user-images.githubusercontent.com/8114237/79087858-47f26380-7d73-11ea-87d8-3bc3a22d3083.png)

 I add LightBDD.XUnit2,add My_feature1Tests : FeatureFixture,but it not invoke utofacTestFramework

**Comment by insurwave** [comment]
Hello @archimate ,

Both, `Xunit.Ioc.Autofac` and `LightBDD.XUnit2` projects requires a custom xunit TestFramework and overrides how the test classes are being constructed - it means those libraries won't work together.

LightBDD however supports DI and Autofac, so if you would like to use it, please take a look at:
* https://github.com/LightBDD/LightBDD/wiki/DI-Containers for the introduction on how DI is integrated with LightBDD
* https://github.com/LightBDD/LightBDD/wiki/DI-Containers#lightbddautofac for integrating Autofac with LightBDD

Please let me know if you have any further questions - I will be happy to help.

Thanks

**Comment by Suremaker** [comment]
Hello @archimate ,

Both, `Xunit.Ioc.Autofac` and `LightBDD.XUnit2` projects customises TestFramework and overrides how the test classes are being constructed - it means those libraries won't work together.

LightBDD however supports DI and Autofac, so if you would like to use it, please take a look at:
* https://github.com/LightBDD/LightBDD/wiki/DI-Containers for the introduction on how DI is integrated with LightBDD
* https://github.com/LightBDD/LightBDD/wiki/DI-Containers#lightbddautofac for integrating Autofac with LightBDD

Please let me know if you have any further questions - I will be happy to help.

Thanks
