### ISSUE TITLE
System.InvalidOperationException : LightBddScopeAttribute is not defined in the project

### ISSUE THREAD

**Issue by levirgon** [LightBDD/LightBDD#218]
System.InvalidOperationException : LightBddScopeAttribute is not defined in the project. Please ensure that following attribute, or attribute extending it is defined at assembly level: [assembly:LightBddScopeAttribute]

**Comment by Suremaker** [comment]
Hey @levirgon. I understand you are trying to use Lightbdd in your project and got this error.

You need to follow the message and add the `[assembly:LightBddScopeAttribute]` in the project where you want to write LightBDD tests.

Details are described on: https://github.com/LightBDD/LightBDD/wiki/Quick-Start#choosing-integration

Example: https://github.com/LightBDD/LightBDD/blob/master/examples/Example.LightBDD.XUnit2/ConfiguredLightBddScopeAttribute.cs
