### ISSUE TITLE
hide step params in report

### ISSUE THREAD

**Issue by krt-c** [LightBDD/LightBDD#229]
#### Description
Is it possible to hide parameters for function steps? I have a step which takes a delegate func<> as param and i dont want to show it in the report....

i created new format attribute where I returned an empty string or null to hide the param but just shows "" i would like to hide the parameters completely...  

```
public Task A_test_action_is_requested([Hide] Func<ClientCommandFactory, Task> func) => func.Invoke(_builder);
```
current result:
STEP 2/5: WHEN A test action is requested [func: ""].

expected result:
STEP 2/5: WHEN A test action is requested

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hey @krt-c,

It is not possible to hide the parameters from step method (the only exception is `this` parameter, if you use the extension method) - please see the [Practices and patterns](https://github.com/LightBDD/LightBDD/wiki/Scenario-State-Management#practices-and-patterns) how to page describing this behaviour.

The reason for it is the test clarity and the convention that any parameters passed to the steps have business meaning, while the internal, non-business-related parameters are passed behind the scene.

What would be worth asking here is why do you want to hide this parameter?
* is it always the same function that you pass, thus it has no meaning for the scenario? If so, why not initializing it in the fixture constructor or in [context object](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#contextual-scenarios) (if you use one) or use other method described on [Scenario State Management](https://github.com/LightBDD/LightBDD/wiki/Scenario-State-Management) page.
* is it a scenario-specific function so each scenario or step may get the different one? If so, then it sounds like it has a special business meaning and it may be worth displaying some details about it after all - you could use then the formatter to prettify it.

Now, if none of the recommendations works for your case, there is a way to achieve it (but at the cost of the readability of the scenario):

```c#
public class My_feature : FeatureFixture
{
    private ClientCommandFactory _factory;
    private string _message;

    [Scenario]
    public async Task Running_test_actions()
    {
        await Runner.RunScenarioAsync(
            _ => Given_a_factory(),
            _ => With(MySecretiveFunc).When_a_test_action_is_requested(),
            _ => Then_I_should_get_message("Hello: some object"));
    }

    private Task Given_a_factory()
    {
        _factory = new ClientCommandFactory();
        return Task.CompletedTask;
    }

    private Task Then_I_should_get_message(string message)
    {
        Assert.Equal(_message, message);
        return Task.CompletedTask;
    }

    private async Task MySecretiveFunc(ClientCommandFactory factory)
    {
        await Task.Delay(500);
        _message = $"Hello: {factory.Create()}";
    }

    private TestActionRunner With(Func<ClientCommandFactory, Task> func) => new TestActionRunner(_factory, func);
}

class ClientCommandFactory
{
    public string Create() => "some object";
}

class TestActionRunner
{
    private readonly ClientCommandFactory _factory;
    private readonly Func<ClientCommandFactory, Task> _func;

    public TestActionRunner(ClientCommandFactory factory, Func<ClientCommandFactory, Task> func)
    {
        _factory = factory;
        _func = func;
    }

    public Task When_a_test_action_is_requested() => _func.Invoke(_factory);
}
```

```
SCENARIO: Running test actions
  STEP 1/3: GIVEN a factory...
  STEP 1/3: GIVEN a factory (Passed after 5ms)
  STEP 2/3: WHEN a test action is requested...
  STEP 2/3: WHEN a test action is requested (Passed after 513ms)
  STEP 3/3: THEN I should get message "Hello: some object"...
  STEP 3/3: THEN I should get message "Hello: some object" (Passed after 1ms)
  SCENARIO RESULT: Passed after 537ms
```

When you specify a step to execute and use the method chaining, LightBDD will print only the most outer (last) method, thus for
```
_ => With(MySecretiveFunc).When_a_test_action_is_requested(),
```
it will ignore the `With()` part and only render the `When_a_test_action_is_requested()` method, which itself does not have any parameters.

This way you can pass your internal state via `With()` method and achieve what you want. 
The cost is:
* readability of the scenario
* additional `With()` method
* additional wrapping object (`TestActionRunner` in this case) for the hidden internal state.

I hope this helps.
