### ISSUE TITLE
Adding file attachments to scenario steps

### ISSUE THREAD

**Issue by adrian-herscu** [LightBDD/LightBDD#255]
#### Description
Test reports should support attachment of screenshots or other text files as a proof of actual result(s) retrieved during tests' execution.

This feature can be found in other BDD frameworks.

**Comment by Suremaker** [comment]
Hello @adrian-herscu ,

Thanks for raising this request. It makes sense and I will consider it when implementing #133 .

**Comment by Suremaker** [comment]
Implementation progress
* [ ] Mechanism to capture file attachments by the engine
* [ ] Progress Notification of file attachment during test execution
* [ ] Add file attachment links to text report
* [ ] Add file attachment links to xml report
* [ ] Add file attachment links to html report
