### ISSUE TITLE
reporting complex type step parameters

### ISSUE THREAD

**Issue by adrian-herscu** [LightBDD/LightBDD#256]
#### Description
Step parameters of complex types are reported as fully qualified type name.

Maybe there is/(should be) a method for controlling the rendering of such types?

**Comment by Suremaker** [comment]
Hello @adrian-herscu ,

LightBDD supports various ways to format step parameters. Please take a look here and hopefully you'll find the method suiting your needs: https://github.com/LightBDD/LightBDD/wiki/Formatting-Parameterized-Steps#formatting-parameter-values

**Comment by adrian-herscu** [comment]
Found `[Format("{0:£0.00#}")]`

Would like something like
```
[Format($"{o.Property} or/and {o.Method}")]
```
as a means to format any kind of object, even those which are runtime/library provided; possible?

**Comment by adrian-herscu** [comment]
Yeap... This means writing something like:
```
    class TimeSpanFormatter : IValueFormatter
    {
        public string FormatValue(object value, IValueFormattingService formattingService)
        {
            var timespan = (TimeSpan)value;
            return timespan.ToString();
        }
    }
```
for every type :(

**Comment by Suremaker** [comment]
I am finding it difficult to understand what do you want to achieve.

The code you have presented is unnecessary as the `.ToString()` formatting is a default behaviour, as per documentation https://github.com/LightBDD/LightBDD/wiki/Formatting-Parameterized-Steps#formatting-parameter-values (point 6). It means you do not need to do it for the types that has natural formatting like TimeSpan, DateTime, primitive types etc.

For everything else you have other options to format values, described under the same documentation link. 

If you have a special requirement,  you can write the explicit formatter as per your example.

If you want to have a generic formatting method for multiple types, use `IConditionalValueFormatter` and specify what types it applies in `CanFormat()`, as described in https://github.com/LightBDD/LightBDD/wiki/Formatting-Parameterized-Steps#formatting-with-preconfigured-formatters


Finally, if you can modify your classes, you can implement your formatting via `ToString()` override or by implementing `ISelfFormatable` interface on the type you want to format, as per: https://github.com/LightBDD/LightBDD/wiki/Formatting-Parameterized-Steps#formatting-with-iselfformattable

**Comment by adrian-herscu** [comment]
Still... I have:

```csharp
internal class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
{
    protected override void OnConfigure(LightBddConfiguration configuration)
    {
        Log.Trace($"configuring {configuration}");

       configuration
            .ValueFormattingConfiguration()
            .RegisterExplicit(typeof(Application), new ApplicationFormatter());
        configuration
            .ValueFormattingConfiguration()
            .RegisterExplicit(typeof(IConstraint), new MatcherFormatter());
```

and

```csharp
class ApplicationFormatter : IValueFormatter
{
    public string FormatValue(object value, IValueFormattingService formattingService)
    {
        var application = value as Application;
        return ">>>>>"+application.Name;
    }
}

```
and nothing happens :(

**Comment by Suremaker** [comment]
@adrian-herscu ,

To give you an example, please take a look at the following code:

```c#
public class My_feature : FeatureFixture
{
    private readonly Application _application = new()
    {
        Name = "Application",
        Constraints = new IConstraint[] { new ConstraintA { Name = "A" }, new ConstraintB { Name = "B" } }
    };

    [Scenario]
    public void Formatted_scenario()
    {
        Runner.RunScenario(_ => Given_I_have_an_application(_application));
    }

    private void Given_I_have_an_application(Application application)
    {
    }
}
```
This is the smallest fixture that does nothing except passing the `_application` object as a parameter to the step.

```c#
class Application
{
    public string Name { get; set; }
    public IConstraint[] Constraints { get; set; }
}
interface IConstraint
{
    public string Name { get; set; }
}
class ConstraintA : IConstraint
{
    public string Name { get; set; }
}
class ConstraintB : IConstraint
{
    public string Name { get; set; }
}
```
The types describing application and the constraints.

```c#
class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
{
    protected override void OnConfigure(LightBddConfiguration configuration)
    {
        configuration.ValueFormattingConfiguration()
            .RegisterExplicit(typeof(Application), new ApplicationFormatter())
            .RegisterGeneral(new ConstraintFormatter());
    }

    protected override void OnSetUp()
    {
    }

    protected override void OnTearDown()
    {
    }
}
```
Formatter registration. The `ApplicationFormatter` is registered explicitly as it works on explicit type. The `ConstraintFormatter` works against interface (so possibly multiple different implementations) thus it is registered as general formatter.

```c#
class ApplicationFormatter : IValueFormatter
{
    public string FormatValue(object value, IValueFormattingService formattingService)
    {
        var app = (Application)value;
        return $"App: {app.Name}, Constraints: [{formattingService.FormatValue(app.Constraints)}]";
    }
}
```
The formatter uses `formattingService` to format constraints array to allow using array formatters and then specific formatters for the array members, such as `ConstraintFormatter`.


```c#
class ConstraintFormatter : IConditionalValueFormatter
{
    public string FormatValue(object value, IValueFormattingService formattingService)
    {
        var constraint = (IConstraint)value;
        return $"{constraint.Name} ({constraint.GetType().Name})";
    }

    public bool CanFormat(Type type) => type.IsAssignableTo(typeof(IConstraint));
}
```
This formatter formats types implementing `IConstraint` interface and it prints the `Name` property as well as value type.

Outcome:
```
SCENARIO: Formatted scenario
  STEP 1/1: GIVEN I have an application "App: Application, Constraints: [A (ConstraintA), B (ConstraintB)]"...
  STEP 1/1: GIVEN I have an application "App: Application, Constraints: [A (ConstraintA), B (ConstraintB)]" (Passed after 6ms)
  SCENARIO RESULT: Passed after 23ms
```

![image](https://user-images.githubusercontent.com/1894621/173253993-df5eb4d5-aa7c-4232-a07e-2be982cc398a.png)

**Comment by Suremaker** [comment]
> Still... There is something I cannot figure out.
I need to handle all types of NUnit constraints, e.g. SubstringConstraint, EqualConstraint, etc.
All these are subtypes of IConstraint.
When I am registering a formatter for IConstraint it is never called.
But when I am registering for the actual types these are called.
Is there any way to make it work for all subtypes?
> Maybe... Using the ConditionalValueFormatter?

Yes, this is the case. I have presented it in the example above. If you need a support for multiple types implementing interface, you need to use `ConditionalValueFormatter`.

---

By the way, LightBDD has own set of expectation tree that is integrated with step parameters:
https://github.com/LightBDD/LightBDD/wiki/Advanced-Step-Parameters#verifiable-class-and-expectto-expressions

I am not sure what do you want to achieve but perhaps this would help you.

**Comment by adrian-herscu** [comment]
I am building a little framework for testing Windows desktop applications with FlaUI.

I have generic step definitions like these:
```csharp
    public TSelf Then_the_title(Constraint matcher)
        => Eventually(() => CurrentWindow.Title, matcher);

    public CalculatorSteps Then_the_result(Constraint matcher)
        => Eventually(() => CurrentWindow
                .FindFirstByXPath("//*[@AutomationId='CalculatorResults']")
                .Name,
            matcher);

  protected TSelf Eventually<T>(Func<T> supplier, Constraint matcher)
        => Retry(() => Execute(() =>
        {
            var value = supplier.Invoke();
            Log.Debug($"got {value}");
            var result = (matcher as IConstraint).Resolve().ApplyTo(value);
            if (!result.IsSuccess)
                throw new AssertionException(
                    $"Expected: {result.Description}\r\nBut was: {result.ActualValue}");
            return Self;
        }));
```
`Retry` is implemented with the Polly library <https://github.com/App-vNext/Polly>
`Execute` contains a bit of logic that checks a `DryRun` flag; if true nothing is executed.

Everything works pretty good except the formatting of constraints, which are rendered sometimes like:

> THEN the title [matcher: "<equal "Calculator">"] 

but sometimes like:

> THEN the html report [matcher: "<unresolved <contains>>"]

Here is my formatter:

```csharp
class MatcherFormatter : IConditionalValueFormatter
{
    public string FormatValue(object value, IValueFormattingService formattingService)
    {
        var constraint = value as Constraint;
        return ">"+constraint.Description;    // ***note the > at the beginning
    }

    bool IConditionalValueFormatter.CanFormat(Type type)
        => type.IsAssignableTo(typeof(Constraint));
}
```

and it is registered like this:

```csharp
        configuration
            .ValueFormattingConfiguration()
            .RegisterExplicit(typeof(Constraint), new MatcherFormatter());
```

I checked few types of constraints and all are assignable to `Constraint`:
```csharp
            Constraint c = Is.EqualTo("kuku");
            c = Contains.Substring("foo");
            c = Has.Property("Baz").Contain("888").IgnoreCase;
```

Unfortunately my formatter is not called in any case.
Tried with `IConstrain` too... Same result :(

**Comment by Suremaker** [comment]
Hey @adrian-herscu ,

Try changing `.RegisterExplicit(typeof(Constraint), new MatcherFormatter());` to `.RegisterGeneral(new MatcherFormatter());`.
I bet that not all constraints are really of `Constraint` type which would match your problem of constraints not being matched `sometimes`.

As I stated in the example above, the `RegisterGeneral` will be used for any type that can be formatted by the formatter, ie for which `CanFormat` method would return true - that is why it is called `general`.  
The `RegisterExplicit` means that the formatter will be used only for `Constraint` type but no other types nor the ones that derive from it.

**Comment by adrian-herscu** [comment]
> Hey @adrian-herscu ,
> 
> Try changing `.RegisterExplicit(typeof(Constraint), new MatcherFormatter());` to `.RegisterGeneral(new MatcherFormatter());`. I bet that not all constraints are really of `Constraint` type which would match your problem of constraints not being matched `sometimes`.
> 

        Assert.True(typeof(StringConstraint).IsAssignableTo(typeof(Constraint)));
        Assert.True(typeof(EqualConstraint).IsAssignableTo(typeof(Constraint)));
        Assert.True(typeof(ContainsConstraint).IsAssignableTo(typeof(Constraint)));

(checked now, all true)

> As I stated in the example above, the `RegisterGeneral` will be used for any type that can be formatted by the formatter, ie for which `CanFormat` method would return true - that is why it is called `general`. The `RegisterExplicit` means that the formatter will be used only for `Constraint` type but no other types nor the ones that derive from it.

**Comment by Suremaker** [comment]
Amazing, so `RegisterGeneral` approach would work then.

Let me know if you got finally it working.

**Comment by Suremaker** [comment]
Just one more note:

> Assert.True(typeof(StringConstraint).IsAssignableTo(typeof(Constraint)));
> Assert.True(typeof(EqualConstraint).IsAssignableTo(typeof(Constraint)));
> Assert.True(typeof(ContainsConstraint).IsAssignableTo(typeof(Constraint)));
> (checked now, all true)

This proves that `StringConstraint` and others derives from `Constraint`, but it does not mean they are exactly the same types, i.e. `typeof(EqualConstraint) != typeof(Constraint)`. `RegisterExplicit` check type to be exactly the one as specified.

The `RegisterGeneral` is a way to go in your case
