### ISSUE TITLE
Unable to resolve DI in Azure pipelines.

### ISSUE THREAD

**Issue by asos-nareshnagpal** [LightBDD/LightBDD#266]
#### Description

Getting this error :  **Unhandled exception. System.InvalidOperationException: LightBddScopeAttribute is not defined in the project. Please ensure that following attribute, or attribute extending it is defined at assembly level: [assembly:LightBddScopeAttribute]**

The tests run fine on local Visual Studio (.Net 6) and its able to recognize the ConfiguredLightBddScopeAttribute. However when running the test cases on Azure DevOps pipeline, the project compiles fine but when running test it give above error. 

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello @asos-nareshnagpal ,

We are executing the lightbdd tests on Azure DevOps with no issues.

Most likely you are trying to execute these tests indirectly via other assembly. Please check if you have any custom runners that try to load and run these tests or if you are inheriting tests defined in other assembly.

You should be able to execute locally `dotnet test` on your solution. If that pass and your CI/CD follows the same pattern the test should run.

**Comment by asos-nareshnagpal** [comment]
Hi @Suremaker , 

I just ran dotnet test as you advised on my local machine and started getting the same error which I am getting on CI/CD. Although it works fine when I select the test explorer in Visual Studio and run the test. 

Is there any additional step that needs  to be done while using dotnet test command?

Thanks
Naresh

**Comment by Suremaker** [comment]
Hi @asos-nareshnagpal ,
The quick start for LightBDD presents on how to integrate with it: https://github.com/LightBDD/LightBDD/wiki/Quick-Start

There are also examples present here: https://github.com/LightBDD/LightBDD/tree/master/examples

Putting the attribute should be sufficient to run the tests - I assume here that you put the attribute to the assembly where you defined your tests.

Please check that:
* You have matching versions of LightBDD packages used in the project (all 3.x).
* You are not mixing LightBDD for xunit, nunit, microsoft tests - i.e.  you should choose and use one (as described in quick start).

If you have multiple assemblies with tests, please tell me more about the project structure, but generally the attribute should be present in all assemblies with LightBDD tests.

**Comment by asos-nareshnagpal** [comment]
my bad, the problem is only there only on CI/CD pipeline and Not locally. When I ran dotnet test locally, it failed initially because I had temporarily commented out assembly attribute in ConfiguredLightBddScopeAttribute class as shown. On un-commenting, the tests run fine on local machine. But  Build pipeline still gives the error 

![image](https://user-images.githubusercontent.com/108878301/187427200-3674b7d4-361c-4b3a-8adc-9a9ba9f1528f.png)

Note : I have matching versions of LightBDD (3.5) and using NUnit only.

**Comment by asos-nareshnagpal** [comment]
One difference I noticed is that the local test execution uses Microsoft (R) Test Execution Command Line Tool Version 17.2.0  while build server uses Microsoft (R) Test Execution Command Line Tool Version 17.3.0 . 

I am not able to find any option to use 17.2.0 version on AzureDevOps pipeline.

**Comment by asos-nareshnagpal** [comment]
ok finally I was able to resolve the issue. The actual problem was that my test was trying to access the Azure KeyVault which was failing due to insufficient permissions. However the pipeline was  not giving any such error. It was simply throwing below error 

`The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: LightBddScopeAttribute is not defined in the project. Please ensure that following attribute, or attribute extending it is defined at assembly level: [assembly:LightBddScopeAttribute] at LightBDD.NUnit3.Implementation.NUnit3FeatureCoordinator.GetInstance() at LightBDD.NUnit3.LightBddScopeAttribute.AfterTest(ITest test)`

The pipeline was using ubuntu host agent. I changed to windows agent and then started getting the actual key vault error in addition to above error. 

I guess the error "missing LightBddScopeAttribute" is coming in  because of finally statement in LightBddScopeAttribute class where Instance is not properly constructed yet and we are trying to dispose it.

` public void AfterTest(ITest test)
        {
            try
            {
                OnTearDown();
            }
            finally
            {
                NUnit3FeatureCoordinator.GetInstance().Dispose();
            }
        }`

Please note if I omit the assembly attribute all together from code then error is same but that's at the beginning of DI resolution. But this error came in TearTown as some other exception (keyVault in my case) has happened.  May be a Null check in Finally block could help.
