### ISSUE TITLE
Usage along with custom xunit fixture

### ISSUE THREAD

**Issue by harish-venkataramanan-cko** [LightBDD/LightBDD#279]
Everything about this library is great! Thanks, How can we use FeatureFixture along with a custom xunit fixture, eg: IGlobalFixture<T> that is used to create T once and used across all tests that run parallely? When I look into the code, I can only see that IClassFixture<> and ICollectionFixture<> are supported. The current error is that T is not getting instantiated by xunit as the executor/runner cannot recognize the IGlobalFixture<> interface

do you have any pointers? Thanks

**Comment by Suremaker** [comment]
Hi @harish-venkataramanan-cko,

I am not sure how the `IGlobalFixture` works as this does not look to be a standard xunit interface - I would need to get some more context on how are you wiring it up to xunit to be able to assist you.

Having said that, LightBDD has a support for DI and using singletons in the scenario.
The easiest way would be to retrieve the singleton dependency as part of the steps, by following https://github.com/LightBDD/LightBDD/wiki/DI-Containers#programmatic-access-to-di-container documentation.

The dependency configuration is described here: https://github.com/LightBDD/LightBDD/wiki/DI-Containers#di-implementations (you can use default LightBDD container, Autofac or standard Microsoft one).

The following example uses the default DI:
```c#
internal class ConfiguredLightBddScopeAttribute : LightBddScopeAttribute
{
    protected override void OnConfigure(LightBddConfiguration configuration)
    {
        configuration.DependencyContainerConfiguration().UseDefault(OnConfigure);
    }

    private void OnConfigure(IDefaultContainerConfigurator ctx)
    {
        ctx.RegisterType<Greeter>(InstanceScope.Single);
    }

    protected override void OnSetUp()
    {
        // code executed before any scenarios
    }

    protected override void OnTearDown()
    {
        // code executed after all scenarios
    }
}

internal class Greeter
{
    // Guid used to present that class is instantiated once
    private readonly Guid _guid = Guid.NewGuid();

    public string GetGreetings(ITestOutputHelper helper)
    {
        helper.WriteLine($"Hello from {_guid}");
        return "Hello!";
    }
}

public class Greetings_feature : FeatureFixture
{
    private Greeter _greeter;
    private string _greeting;

    [Scenario]
    public void Scenario_1()
    {
        Runner.RunScenario(
            _ => Given_I_have_my_dependencies_set(),
            _ => When_I_ask_for_a_greeting(),
            _ => Then_I_will_receive_text("Hello!"));
    }

    [Scenario]
    public void Scenario_2()
    {
        Runner.RunScenario(
            _ => Given_I_have_my_dependencies_set(),
            _ => When_I_ask_for_a_greeting(),
            _ => Then_I_will_receive_text("Hello!"));
    }

    private void Then_I_will_receive_text(Verifiable<string> text)
    {
        text.SetActual(_greeting);
    }

    private void When_I_ask_for_a_greeting()
    {
        _greeting = _greeter.GetGreetings(TestOutput);
    }

    private void Given_I_have_my_dependencies_set()
    {
        _greeter = StepExecution.Current.GetScenarioDependencyResolver().Resolve<Greeter>();
    }
}
```
The sample execution gives this outcome (`dotnet test --logger:"console;verbosity=detailed"`)
```
  Passed LightBDDTests1.Greetings_feature.Scenario_2 [55 ms]
  Standard Output Messages:
 SCENARIO: Scenario 2
   STEP 1/3: GIVEN I have my dependencies set...
   STEP 1/3: GIVEN I have my dependencies set (Passed after 7ms)
   STEP 2/3: WHEN I ask for a greeting...
 Hello from d1a6f4c1-df6f-4fa0-96f0-fcd4d36d9777
   STEP 2/3: WHEN I ask for a greeting (Passed after <1ms)
   STEP 3/3: THEN I will receive text "expected: equals 'Hello!'"...
   STEP 3/3: THEN I will receive text "Hello!" (Passed after 2ms)


  Passed LightBDDTests1.Greetings_feature.Scenario_1 [55 ms]
  Standard Output Messages:
 SCENARIO: Scenario 1
   STEP 1/3: GIVEN I have my dependencies set...
   STEP 1/3: GIVEN I have my dependencies set (Passed after 7ms)
   STEP 2/3: WHEN I ask for a greeting...
 Hello from d1a6f4c1-df6f-4fa0-96f0-fcd4d36d9777
   STEP 2/3: WHEN I ask for a greeting (Passed after <1ms)
   STEP 3/3: THEN I will receive text "expected: equals 'Hello!'"...
   STEP 3/3: THEN I will receive text "Hello!" (Passed after 2ms)
```

Please note that both scenarios used greeter with the same guid (singleton).

_Note: The dependencies configured with LightBDD DI will be disposed upon termination._

Also, LightBDD has classes helping you with accessing the limited pool of the dependencies (like Selenium Drivers) - the details of using them are described here: https://github.com/LightBDD/LightBDD/wiki/DI-Containers#resourcepool-and-resourcehandle where actual LightBDD acceptance tests are using them here: https://github.com/LightBDD/LightBDD/blob/master/test/LightBDD.AcceptanceTests/ConfiguredLightBddScopeAttribute.cs#L34 and here https://github.com/LightBDD/LightBDD/blob/master/test/LightBDD.AcceptanceTests/Features/HtmlReportContext.cs#L76 (please bear in mind that these tests though uses [contextual scenarios](https://github.com/LightBDD/LightBDD/wiki/Scenario-Steps-Definition#contextual-scenarios)).

Please let me know if that helps and feel free to share more details if you have further issues with it!

Have a great weekend!

**Comment by harish-venkataramanan-cko** [comment]
Hi @Suremaker, thanks for the response. Apologies for an unclear description of the issue. I will try to explain better.

I already have something similar to LightBDD's FeatureFixture.

This is, for the sake of description called IGlobalFixture. This is similar to IClassFixture and ICollectionFixture of xunit. However, the problem with the xunit provided ones is that they are not suitable for my use case. i.e. I want to be able to create a fixture (eg: in-memory dotnet test server for integration tests) once, and then run all the tests across all the classes parallely. 
In order to achieve that I created a new interface IGlobalFixture and then implemented the necessary framework and runners so that the IGlobalFixture is understood and discovered by xunit. Please check more context in this [SO thread](https://stackoverflow.com/a/44534216/1301703).

By looking at the code, [LightBDD's xunit integration only looks for IClassFixture and ICollectionFixture](https://github.com/LightBDD/LightBDD/blob/8c034e1017a048256f900f3cd363312868b8ccd4/src/LightBDD.XUnit2/Implementation/Customization/TaskExecutor.cs#L13)

So, the question is, how can I make LightBDD aware of my custom interface? Hope that clarifies the issue.
Enjoy your weekend!

**Comment by Suremaker** [comment]
In that case please take a look at the following tutorial that instantiates a single server instance to be later used by scenarios run in parallel: https://github.com/LightBDD/LightBDD.Tutorials/tree/master/WebApiServiceTests#one-test-server-instance

I would suggest following this approach as it is relatively easy to wire up, where [ConfiguresLightBBBScope](https://github.com/LightBDD/LightBDD.Tutorials/blob/master/WebApiServiceTests/CustomerApi.ServiceTests/ConfiguredLightBddScope.cs) offers you entry points to initialize and dispose your server instance.

To make LightBDD work with `IGlobalFixture` you may need to copy and modify some of the LightBDD - xunit integration classes (https://github.com/LightBDD/LightBDD/tree/master/src/LightBDD.XUnit2/Implementation/Customization) which most likely will be much more complicated and introduce unnecessary boilerplate code.

**Comment by Suremaker** [comment]
Hi @harish-venkataramanan-cko , as I did not hear from you I presume this problem has been answered.

I have just completed a tutorial that shows usage of DI injected dependencies to the scenarios as well as sharing the global instances of TestServer. You may use it as an inspiration for your tests too.

Here is the link: https://github.com/LightBDD/LightBDD.Tutorials/tree/master/WebApiWithDependenciesServiceTests
