### ISSUE TITLE
Tests not discoverable in VS 2017

### ISSUE THREAD

**Issue by ykeysergit** [LightBDD/LightBDD#31]
Despite installing Nuget package xunit.visualstudio.runner, the test is still not discoverable. When I use [Fact], it finds the test. What is the difference here?

**Comment by Suremaker** [comment]
Hello,

I just tried it out in Visual Studio 2017 Community Edition 15.1 (26403.3).

I have created two projects:
* xUnit Test Project (.NET Core)
* Class Library (.NET Framework 4.6.2)

In both I added following packages (plus their dependencies):
* LightBDD.XUnit2 2.1.0
* xunit.runner.visualstudio 2.2.0

With that setup, when I added following code, I was able to run test from both, Resharper 2017.1.1 as well as from standard Visual Studio runner:
```c#
using LightBDD.Framework.Scenarios.Extended;
using LightBDD.XUnit2;
using Xunit.Abstractions;
[assembly: LightBddScope]

namespace MyTestProject1
{
    public class My_feature : FeatureFixture
    {
        public My_feature(ITestOutputHelper output) : base(output)
        {
        }

        [Scenario]
        public void My_scenario()
        {
            Runner.RunScenario(_ => Hello_world());
        }

        private void Hello_world()
        {
        }
    }
}
```

Please ensure that you have `[assembly: LightBddScope]` added to test project, there is no mismatch between xunit versions (as well as all referenced LightBDD packages are of 2.1.0 version).

I hope it will help.

**Comment by ykeysergit** [comment]
I tried running your example...it's still not discovered in VS17 test explorer. Can you confirm Test Explorer is displaying it?

**Comment by Suremaker** [comment]
I have attached sample solution with 2 projects:
[LightBDD_VS2017.zip](https://github.com/LightBDD/LightBDD/files/956527/LightBDD_VS2017.zip)

On my VS 2017 with spec mentioned in first response, I am able to run the tests:
![vs2017_test_run](https://cloud.githubusercontent.com/assets/1894621/25407396/0cf2e89e-2a02-11e7-9673-e601a0c88127.PNG)

**Comment by Suremaker** [comment]
I have also updated my VS to the newest version and checked that project works:
![vs2017_26403 7](https://cloud.githubusercontent.com/assets/1894621/25407652/18e7d460-2a03-11e7-8ba6-a73b028c2c43.PNG)

I had to recompile the project however, as it looked like it did not caught up immediately that there are tests present.

**Comment by ykeysergit** [comment]
OK. Those test cases appear. May be something on my end...

**Comment by ykeysergit** [comment]
It's working now. Can't reproduce the problem anymore. Thanks for your input!
