### ISSUE TITLE
SkippableScenario

### ISSUE THREAD

**Issue by lemonlion** [LightBDD/LightBDD#337]
#### Description
XUnit [now implements](https://github.com/xunit/samples.xunit/blob/main/DynamicSkipExample/Samples.cs) `SkippableTheory`, allowing you to dynamically skip a test at runtime by throwing a `SkipTestException`.  Since LightBDD `Scenario` doesn't inherit from `SkippableTheory`, is there any LightBDD mechanism to do something similar to the native xunit solution or similar to this [nuget package solution](https://github.com/AArnott/Xunit.SkippableFact)?

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hi,

https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions contains insights on how to ignore tests on class, scenario and step level.

https://github.com/LightBDD/LightBDD/wiki/What-Is-New#lightbdd-311 contains additional insights on how to skip scenarios with InlineData (xunit)

**Comment by lemonlion** [comment]
Thanks for the links - I've read through them and I cant see anything on _dynamically_ skipping tests at _runtime_.  As far as I can tell the documentation talks about statically skipping tests with the `Skip = "{skip reason}`, or using the `IgnoreScenario` attribute to again statically ignore a test.  What I'm looking to do is Skip based on some runtime check, eg

```
[SkippableScenario]
public void MyTest()
{
    if(someRuntimeCheck)
        throw new SkipTestException("This has been skipped because of X");
}
```

...just like XUnit's `SkippableTheory` supports.

My use case is that my Component tests can run using either fakes or with real dependencies.  We use header forwarding to control the outputs of fake dependencies in cases where we want to test bad responses from them.  We can't do that for the real dependencies, so we want to have a config setting "UsingRealDependencies" that, when enabled, those specific tests are skipped for.

**Comment by Suremaker** [comment]
It is in first link, [Steps behaviour](https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions#steps-behavior) section. `StepExecution.Current.IgnoreScenario()`

**Comment by lemonlion** [comment]
> It is in first link, [Steps behaviour](https://github.com/LightBDD/LightBDD/wiki/Tests-Structure-and-Conventions#steps-behavior) section. StepExecution.Current.IgnoreScenario()

Ah, my apologies - I missed that.  Thank you, that's exactly what I need.
