### ISSUE TITLE
Feature: support for scenario descriptions analogous to feature descriptions

### ISSUE THREAD

**Issue by goldsam** [LightBDD/LightBDD#338]
#### Description

My team uses [Zephyr Scale](https://smartbear.com/test-management/zephyr-scale/) for test management, and we've build a custom solution for pushing/synchronizing Zephyr against [LightBdd's XML output](https://github.com/LightBDD/LightBDD/blob/master/schemas/XmlReportFormatterSchema.xsd) using their REST API. This works great for the most part with two exceptions to do model inconsistencies:

1. Zephyr has no concept of a test grouping (i.e. feature) where you can capture a feature description once for all tests in that grouping/feature.
2. LightBDD has no concept of a scenario description.

Our workaround for (1) was to simply replicate the LightBDD's feature description into each test case's description in Zephyr or a custom test case field.

Our scenario steps are often quite lengthy and seem to more frequently be of interest when things break. It would be very useful however to have a brief description that provides context to a test/scenario beyond just a name but without the extensive details captured in the scenario steps.

I propose the following enhancements to introduce a scenario description analogous to a feature description:
- Add a string `Description` property to [`IScenarioInfo`](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Core/Metadata/IScenarioInfo.cs)
- Add `ScenarioDescriptionAttribute` and `IScenarioDescriptionAttribute` analogous to [`FeatureDescriptionAttribute`](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Framework/FeatureDescriptionAttribute.cs) and [`IFeatureDescriptionAttribute`](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Core/Extensibility/IFeatureDescriptionAttribute.cs) respectively
- Extend [XmlReportFormatterSchema.xsd](https://github.com/LightBDD/LightBDD/blob/master/schemas/XmlReportFormatterSchema.xsd) by adding a `<Description>` child element to the `<Scenario>` element.
- Update all [`IReportWriter`](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Core/Reporting/IReportWriter.cs) implementations to respect this property.
- Update relevant documentation.

Although we could perhaps work around the issue using a custom label representation, this is feels clunky and leads to confusion.

I would be happy and willing to work on a PR if you support this proposal.

Also, thank your for your amazing work on this project.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello @goldsam .

Thank you for raising this request - it sounds reasonable and I will be happy to incorporate it into the library.
Please feel free to make the changes and raise the PR against the `master` branch. Upon completion, I will review it and create a new release of LightBDD series 3.x.

I will be happy to cover the documentation changes and all necessary changes to make the release (eg. version bump, etc).

I am looking forward to hearing from you.
Thanks

**Comment by Suremaker** [comment]
Included in LighBDD 3.8.0. Thanks @goldsam for your contribution!
