### ISSUE TITLE
Getting error "LightBddScopeAttribute is not defined in the project"

### ISSUE THREAD

**Issue by nissan** [LightBDD/LightBDD#44]
Following the quick start steps at https://github.com/LightBDD/LightBDD/wiki/Quick-Start but when I run the NUnit test runner I get the error 
```
OneTimeSetUp: System.InvalidOperationException : LightBddScopeAttribute is not defined in the project. Please ensure that following attribute, or attribute extending it is defined at assembly level: [assembly:LightBddScopeAttribute]
  Exception doesn't have a stacktrace
```

Attaching the zip file of the VS Solution I was working with.
[TheSoco.O365.Extensions.zip](https://github.com/LightBDD/LightBDD/files/1241152/TheSoco.O365.Extensions.zip)

Much thanks for any help solving this issue.

**Comment by Suremaker** [comment]
Hello,

The LightBDD.NUnit3 integration requires a `[assembly:LightBddScope]` to be present in the test assembly to run the tests.
In the sample code that is attached in the ticket, it is enough to add that line above the namespace declaration:
```c#
[assembly:LightBddScope]
namespace TheSoco.O365.Extensions.Test
{
  [TestFixture]
  [FeatureDescription(
    @"In order to test an SPFx webpart
    As a Solution Collective Software Developer
    I want to login to my Office 365 SharePoint test tenant")]
  [Label("Story-1")]
  public partial class SharePoint_Feature
  {
    [Scenario]
    [Label("Ticket-1")]
    [ScenarioCategory("Authentication")]
    public void Successful_0365_Login() => Runner.RunScenario(
        Given_the_user_is_about_toLogin,
        Given_the_user_entered_valid_username,
        Given_the_user_entered_valid_password,
        Given_the_user_entered_valid_O365_address,
        When_the_user_clicks_login_button,
        The_the_login_should_be_successful,
        Then_the_Intranet_homepage_should_load
      );

  }
}
```

The integration details are described on [Test Framework Integrations](https://github.com/LightBDD/LightBDD/wiki/Test-Framework-Integrations) wiki page.

I see your point that [Quick Start](https://github.com/LightBDD/LightBDD/wiki/Quick-Start) does not tell anything about that - thank you for pointing it out!
I have updated the page with a section describing the required integration code now: https://github.com/LightBDD/LightBDD/wiki/Quick-Start#choosing-integration

I hope it helps.
