### ISSUE TITLE
Reports are not generated when using NUnit 2.6.4 test runner

### ISSUE THREAD

**Issue by ssg47** [LightBDD/LightBDD#72]
The documentation should clarify that reports are only generated when using the NUnit Test Adapter in Visual Studio and not when running the `nunit.exe` GUI.

**Comment by Suremaker** [comment]
The Visual Studio is IDE is not required to generate the reports. Nunit console runner is generating them as well.

I am pretty sure that nunit GUI would produce them too, as the report generation is triggered after all tests are finished. Perhaps the output path is different in that scenario (I will verfiy if after I come back).

Also please ensure that you are using LightBdd.NUnit2 2.3.0 package and not one of 1.x series.

**Comment by ssg47** [comment]
It's definitely v2.3.0 - I just checked.  The reports weren't created where specified until I installed the NUnit2 test adapter and ran the tests using Visual Studio.

**Comment by ssg47** [comment]
Found it: the Reports folder was generated in the solution folder.
