### ISSUE TITLE
Report Generation Issues

### ISSUE THREAD

**Issue by nismolo** [LightBDD/LightBDD#86]
We are trying to create a feature in our framework to send the reported generated by lightbdd by email once all tests have been executed but we are getting into some issues. 

The code to send the email is being implemented in the teardown method of the ConfiguredLightBddScopeAttribute class but it seems that the report is generated after the this method is executed. I think the below code confirms it since the report generator is within the dispose method.

`internal void TearDown()
        {
            try
            {
                OnTearDown();
            }
            finally
            {
                XUnit2FeatureCoordinator.GetInstance().Dispose();
            }
        }`

`public void Dispose()
        {
            if (_disposed)
                return;
            _disposed = true;

            var results = _results.OrderBy(r => r.Info.Name.ToString()).ToArray();
            foreach (var writer in _writers)
                writer.Save(results);
        }`

Another issue which I came across was that the report is not overwriten if the file already exist is this intended? This issue only happens to new configured FileWriters

**Comment by Suremaker** [comment]
Hello,

To answer your first question: yes this is the behavior. The OnTearDown() method gives an opportunity to perform cleanup before LightBDD code is disposed. The report generation happens after that, on disposal. Currently there is no extensibility point allowing to execute code after reports are generated.

Currently I see 2 options to implement emailing:
* run it as a separate post-build step, where at that point all the reports will be in place (I think normally I would go this way, as emailing is a similar process to archiving reports etc),
* implement [IReportWriter](https://github.com/LightBDD/LightBDD/blob/master/src/LightBDD.Core/Reporting/IReportWriter.cs) to send reports via email and register it as a last report writer with code: 
```c#
configuration
                .ReportWritersConfiguration()
                .Add(new MyEmailingReporter());
```

> Another issue which I came across was that the report is not overwriten if the file already exist is this intended? This issue only happens to new configured FileWriters

There is no difference between default report writers and customized ones. And the files should be overwritten. Often I run the tests locally and then check the reports, so they are properly updated. Perhaps you are trying to access them before report writters have a chance to save a new report?

**Comment by Suremaker** [comment]
One more note on using `IReportWriter` approach:

As the report generators are implemented in registration order (where default ones are first), the `MyEmailingReporter` will be called when reports generated by others will already be in place.


The another variation for this would be to make the MyEmailingReporter a decorating proxy that would accept `ReportFileWriter` or `ReportFileWriter[]` in constructor where implementation will be as follows:
```c#
class MyEmailingReporter : IReportWriter
{
    private readonly ReportFileWriter[] _writers;

    public MyEmailingReporter(params ReportFileWriter[] writers)
    {
        _writers = writers;
    }
    public void Save(params IFeatureResult[] results)
    {
        foreach (var writer in _writers)
            writer.Save(results);
        SendEmail(_writers.Select(x => x.FullOutputPath).ToArray());
    }

    private void SendEmail(string[] attachmentPaths)
    {
        // send email
    }
}
```

and register it as follows:
```c#
protected override void OnConfigure(LightBddConfiguration configuration)
{
    configuration
        .ReportWritersConfiguration()
        .Clear() // remove defaults
        .Add(new MyEmailingReporter(
            new ReportFileWriter(new HtmlReportFormatter(), "~\\Reports\\HtmlReport.html"),
            new ReportFileWriter(new XmlReportFormatter(), "~\\Reports\\XmlReport.xml")
            ));
}
```

The custom reports registration is described here: https://github.com/LightBDD/LightBDD/wiki/Generating-Reports#report-generation-configuration

**Comment by Suremaker** [comment]
I updated the [Generating-Reports](https://github.com/LightBDD/LightBDD/wiki/Generating-Reports#post-processing-generated-reports) wiki page with that sample as well as added `OnSetUp()/OnTearDown()` method description on [LightBDD-Configuration](https://github.com/LightBDD/LightBDD/wiki/LightBDD-Configuration) page.

**Comment by nismolo** [comment]
Hey we implemented your proposed solution by creating a new email report and got the expected results.

Thanks mate! 👍 Thanks for updating documentation!

**Comment by Suremaker** [comment]
I'm glad it works good for you :)
