### ISSUE TITLE
path for Reports are broken on Unix systems

### ISSUE THREAD

**Issue by tim-klug** [LightBDD/LightBDD#87]
#### Description
When using LightBDD on Unix based systems, the directories are not constructed correctly. Directories are hardcoded with double backslashes \\ and there fore do not fit for Unix based systems.

Instead of hardcoding the directory separators use the System.IO.Path.DirectorySeparatorChar to allow setting the correct separator from the system.

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello @tim-klug .
Thank you for fixing the issue. I will release ver 2.3.2 later today.

**Comment by Suremaker** [comment]
The fix is included in LightBDD 2.3.2.
