### ISSUE TITLE
NCrunch fails to execute LightBDD tests: System.InvalidOperationException: FeatureCoordinator of LightBDD.XUnit2.Implementation.XUnit2FeatureCoordinator type is already installed

### ISSUE THREAD

**Issue by Suremaker** [LightBDD/LightBDD#90]
Adding LightBDD scenarios to project monitored by NCrunch ends up with NCrunch reporting following error and executing tests forever:
```
System.InvalidOperationException: FeatureCoordinator of LightBDD.XUnit2.Implementation.XUnit2FeatureCoordinator type is already installed
at LightBDD.Core.Execution.Coordination.FeatureCoordinator.Install(FeatureCoordinator coordinator)
at LightBDD.XUnit2.LightBddScopeAttribute.SetUp()
at LightBDD.XUnit2.Implementation.Customization.TestFrameworkExecutor.RunTestCases(IEnumerable`1 testCases, IMessageSink executionMessageSink, ITestFrameworkExecutionOptions executionOptions)
at Xunit.Sdk.TestFrameworkExecutor`1.RunTests(IEnumerable`1 testCases, IMessageSink executionMessageSink, ITestFrameworkExecutionOptions executionOptions)
at nCrunch.Module.XUnit2.Integration.XUnit2FrameworkRuntimeEnvironment.<>c__DisplayClass3_1.<RunTests>b__3()
```

From the discussion on [NCrunch forum](http://forum.ncrunch.net/yaf_postst2265_Test-status-shows-test-running-forever-but-no-processing-in-the-queue.aspx) it seems that NCrunch process is re-used to execute the next batch of the tests. This contradicts the current LightBDD expectation that tests are started and finished only once within app domain/process in order to properly capture and generate execution reports.

I have briefly spiked an ability to lift that requirement in #25 by using async local context but it appeared not working for the current integration with underlying test frameworks.

As this issue with NCrunch is re-appearing I have opened this ticket to search for other solution (like allowing to start a new test session when previous is already closed).

**Comment by Suremaker** [comment]
With the last change it is now possible to use the same process/AppDomain to execute LightBDD tests multiple times, with the limitation that the process will run one test session at the time.

**Comment by Suremaker** [comment]
As NCrunch executes the tests in the incremental manner (re-runs only altered tests), the generating LightBDD reports from NCrunch sessions is meaningless (and may lead to issues to write report files if the name is static while multiple sessions will try to access it).

To avoid that problems and make execution a bit faster it is worth to disable report generation when tests runs from NCrunch:

```c#
protected override void OnConfigure(LightBddConfiguration configuration)
{
    // configure reports that will be normally generated...
    configuration
        .ReportWritersConfiguration()
        .AddFileWriter<PlainTextReportFormatter>("~\\Reports\\{TestDateTimeUtc:yyyy-MM-dd-HH_mm_ss}_FeaturesReport.txt");

    //... but disable all of them if tests are executed by NCrunch
    if (Environment.GetEnvironmentVariable("NCrunch") == "1")
        configuration.ReportWritersConfiguration().Clear();
}
```

**Comment by areicher** [comment]
@Suremaker Thank you!!  Excellent support!  I hadn't even had time to test and verify this (nor obviously report it here) before you found and fixed this issue I reported to NCrunch! 🥇

**Comment by Suremaker** [comment]
You are welcome :) I hope it will work better now for you.
