### ISSUE TITLE
Dispose Context after each Scenario if Context implements IDisposable

### ISSUE THREAD

**Issue by psibernetic** [LightBDD/LightBDD#94]
#### Description

As far as I can tell and see in debugging, context objects are never disposed. 

I believe it is possible to manually do this in xUnit2 by not using the automatic `.WithContext<T>()` method, but providing an instance and later disposing of it, but that isn't as nice and leaves room for errors.

My scenarios use a local server for testing API round trips. The server is started and destroyed on each call to clean the slate as it were.

#### Progress

- [x] Implement scenario context disposing,
- [x] Implement step context disposing,
- [x] Implement context disposal exception propagation,
- [x] Ensured backward-compatibility,
- [x] Ensured good debugging experience

**Comment by Suremaker** [comment]
Hello,
The use case you have described is definitely valid one. I had a plan to handle the disposable contexts with #59 but I'll implement this one sooner.

Thanks for reporting it.

**Comment by Suremaker** [comment]
Assuming following code:
```c#
class MyContext : IDisposable
{
    private readonly Guid _id = Guid.NewGuid();
    public MyContext()
    {
        TestContext.Out.WriteLine("Creating " + _id);
    }
    public void Dispose()
    {
        TestContext.Out.WriteLine("Disposing " + _id);
    }

    public void Given_something()
    {
    }

    public void When_something()
    {
    }

    public void Then_something()
    {
    }
}

public class My_feature1 : FeatureFixture
{
    [Scenario]
    public void Contextual_scenario()
    {
        Runner
            .WithContext<MyContext>()
            .RunScenario(
                x => x.Given_something(),
                x => x.When_something(),
                x => x.Then_something());
    }

    [Scenario]
    public void Scenario_with_contextual_composite_steps()
    {
        Runner.RunScenario(
            _ => My_contextual_step(),
            _ => My_contextual_step());
    }

    private CompositeStep My_contextual_step()
    {
        return CompositeStep
            .DefineNew()
            .WithContext<MyContext>()
            .AddSteps(
                x => x.Given_something(),
                x => x.When_something(),
                x => x.Then_something())
            .Build();
    }
}
```

The console output will be (LightBDD.NUnit3):
```c#
SCENARIO: Contextual scenario
Creating 78edeaa0-229e-4516-890f-16f5c07f9bb3
  STEP 1/3: GIVEN something...
  STEP 1/3: GIVEN something (Passed after 12ms)
  STEP 2/3: WHEN something...
  STEP 2/3: WHEN something (Passed after <1ms)
  STEP 3/3: THEN something...
  STEP 3/3: THEN something (Passed after <1ms)
Disposing 78edeaa0-229e-4516-890f-16f5c07f9bb3
  SCENARIO RESULT: Passed after 48ms


SCENARIO: Scenario with contextual composite steps
  STEP 1/2: My contextual step...
Creating 92082ce2-1339-464c-a4d1-de7a6f8264a1
  STEP 1.1/1.3: GIVEN something...
  STEP 1.1/1.3: GIVEN something (Passed after <1ms)
  STEP 1.2/1.3: WHEN something...
  STEP 1.2/1.3: WHEN something (Passed after <1ms)
  STEP 1.3/1.3: THEN something...
  STEP 1.3/1.3: THEN something (Passed after <1ms)
Disposing 92082ce2-1339-464c-a4d1-de7a6f8264a1
  STEP 1/2: My contextual step (Passed after 14ms)
  STEP 2/2: My contextual step...
Creating 46009e51-805e-4f03-885c-835fec4f3d7e
  STEP 2.1/2.3: GIVEN something...
  STEP 2.1/2.3: GIVEN something (Passed after <1ms)
  STEP 2.2/2.3: WHEN something...
  STEP 2.2/2.3: WHEN something (Passed after <1ms)
  STEP 2.3/2.3: THEN something...
  STEP 2.3/2.3: THEN something (Passed after <1ms)
Disposing 46009e51-805e-4f03-885c-835fec4f3d7e
  STEP 2/2: My contextual step (Passed after 3ms)
  SCENARIO RESULT: Passed after 19ms
```

### The new behavior

* The `.WithContext<MyContext>()` will **always dispose** disposable context instances,
* The `.WithContext(new MyContext())` will **not dispose context by default**. The reasoning is that as instance is passed explicitly, it may be used somewhere else as well. The caller will have to dispose it on their own. As the method has now an optional parameter `bool takeOwnership = false` it is possible to make context automatically disposed by calling `.WithContext(new MyContext(), true)`,
* The `.WithContext(() => new MyContext())` will **dispose context by default**. The reasoning is that as factory method is being passed it is expected it will produce a new instance on each call. Similarly to method above, it is possible to change default behavior and make context not disposed by calling `.WithContext(() => new MyContext(), false)`,

**Comment by psibernetic** [comment]
Sounds totally reasonable for the API decisions. Good work!

**Comment by Suremaker** [comment]
It is included in LightBDD 2.3.3 now, so feel free to try it out.
Happy New Year :)

**Comment by psibernetic** [comment]
Will do, thanks for the quick turn around, nobody but us is geeking out on NYE haha

**Comment by Suremaker** [comment]
Hey @psibernetic, you may be interested to take a look at #98, as it is possible now to write features without ctor as well as with Collection Fixtures (I believe that constructor was disallowing it in the past)

**Comment by psibernetic** [comment]
I'll be upgrading! Great quality of life upgrade thanks!
